export const maintenance = {
    figure : 'figure src',
    content: `duuududu
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    afsfafasf
    d`
}